# Generated by Django 3.0.3 on 2021-11-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0002_user_info_blist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='money',
            field=models.CharField(default='', max_length=255),
        ),
    ]
