# Generated by Django 3.0.3 on 2021-11-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlinebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='blist',
            field=models.CharField(default='', max_length=255),
        ),
    ]
