// const swaggerAutogen = require('swagger-autogen')()


// const doc = {
//   info: {
//     version: "1.0.0",
//     title: "My API",
//     description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
//   },
//   host: "localhost:3000",
//   basePath: "/",
//   schemes: ['http', 'https']
// }

// const outputFile = './swagger.json'
// const endpointsFiles = ['./app.js','server/routes/*.js']

// swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
//   require('./app.js')           // Your project's root file
// })
const swaggerAutogen = require('swagger-autogen')();

const outputFile = './swagger_output.json'; // 輸出的文件名稱
const endpointsFiles = ['./app.js','server/routes/user_route.js','server/routes/admin_route.js','server/routes/marketing_route.js','server/routes/order_route.js','server/routes/product_route.js',]; // 要指向的 API，通常使用 Express 直接指向到 app.js 就可以
const endpointsFiles2=['server/routes/*.js']

swaggerAutogen(outputFile, endpointsFiles); // swaggerAutogen 的方法
